[window]
decorations = "none"
startup_mode = "Maximized"

[font]
size = 17.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

builtin_box_drawing = true


[colors.primary]
background = "#000000"
foreground = "#00ff00"

[colors.cursor]
text = "#000000"
cursor = "#00ff00"

[colors.selection]
text = "#000000"
background = "#00ff00"