[window]
decorations = "none"
startup_mode = "Maximized"

[font]
size = 17.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#00ff00"

[colors.cursor]
text = "#000000"
cursor = "#00ff00"

[colors.selection]
text = "#000000"
background = "#00ff00"